language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  
install:
- sudo pip install codecov  

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  
after_success:
- bash <(curl -s https://codecov.io/bash)
  
script: phpunit

env:
- MC_API_KEY=someValue